apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-site-deployment
  labels:
    site: peterimkus
spec:
  replicas: 2
  selector:
    matchLabels:
      site: peterimkus
  template:
    metadata:
      labels:
        site: peterimkus
    spec:
      containers:
      - name: pr-site-container
        image: element665/website:1
        ports:
        - containerPort: 80
        resources:          
          requests:
            cpu:    "25m"
            memory: "64Mi"
          limits:
            cpu:    "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: pr-site-service
spec:
  selector:
    site: peterimkus
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30011
  type: NodePort