name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'site/**'
      - 'Dockerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'site/**'
      - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}  

    - name: Build and Push
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag element665/website:$TAG --tag element665/website:latest
        docker push element665/website:$TAG
        docker push element665/website:latest

    - name: Setup Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    - name: Deploy to web server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/webadmin/Website/docker/
          docker compose pull
          docker compose up -d